import { afterEach, expect, it, vi } from 'vitest'

afterEach(() => { vi.unstubAllEnvs(); vi.unstubAllGlobals(); localStorage.clear(); sessionStorage.clear() })

it('uses authorized server yards and rejects stored or build-wide foreign scope', async () => {
  vi.resetModules()
  vi.stubEnv('VITE_API_URL', 'http://api.test')
  vi.stubEnv('VITE_FACILITY_ID', '999')
  localStorage.setItem('trucki-yard-2', '999')
  const fetchMock = vi.fn()
  vi.stubGlobal('fetch', fetchMock)
  const { signInLive, signOutLive } = await import('./live')
  const api = await import('./api')
  const { useSession } = await import('../store/session')
  const response = (user: unknown) => new Response(JSON.stringify({ token: 'test', user }), { status: 200 })
  fetchMock.mockResolvedValueOnce(response({ id: 2, role: 'ADMIN', organisation: { id: 8, name: 'Tenant A', slug: 'a' }, facilities: [{ id: 31, name: 'Yard A', slug: 'a' }] }))
  await signInLive('a', 'synthetic')
  expect(api.facilityId).toBe('31')
  expect(useSession.getState().workspace?.organisation?.name).toBe('Tenant A')
  fetchMock.mockResolvedValueOnce(response({ id: 3, role: 'ADMIN', organisation: { id: 9, name: 'Tenant B', slug: 'b' }, facilities: [{ id: 41, name: 'Yard B', slug: 'b' }] }))
  await signInLive('b', 'synthetic')
  expect(api.facilityId).toBe('41')
  expect(useSession.getState().workspace?.facilities.map(f => f.id)).toEqual([41])
  fetchMock.mockResolvedValueOnce(new Response('{}', { status: 200 }))
  await signOutLive()
  useSession.getState().signOut()
  expect(api.facilityId).toBe('')
  expect(useSession.getState().workspace).toBeNull()
})
