import type {Role} from '../store/session'
import type {RouteKey} from './gates'
export const WALKTHROUGH_ROLES: {role:Role;purpose:string}[] = [
  {role:'ADMIN',purpose:'Configure tenant, sites and staff; register fleet and retain rating evidence.'},
  {role:'DISPATCH_SUPERVISOR',purpose:'Prepare trips and loads, register arrivals, record inspection context and observations.'},
  {role:'OPERATIONS_SUPERVISOR',purpose:'Manage docks, release decisions, physical movement, delivery exceptions and returns.'},
  {role:'FACILITY_MANAGER',purpose:'Oversee site operations, resolve handoffs and review performance.'},
  {role:'COMPLIANCE_OFFICER',purpose:'Independently review evidence and configurations; examine the retained audit trail.'},
  {role:'EXECUTIVE',purpose:'Review performance and evidence without operational write access.'},
]
type Task={id:string;title:string;roles:Role[];route:RouteKey;before:string;action:string;expect:string}
export const WALKTHROUGH_TASKS:Task[] = [
  {id:'consignment',title:'Connect the customer order and its truck loads',roles:['DISPATCH_SUPERVISOR','OPERATIONS_SUPERVISOR','FACILITY_MANAGER','ADMIN'],route:'consignments',before:'Customer order reference, commodity, target quantity and unit are known. Prepare and link each truck trip, then record its delivery plan.',action:'Record a customer consignment. Allocate the matching delivery-plan lines before release. Open each movement from the order dossier to follow the next accountable action.',expect:'One order can span several trucks. Accepted delivery receipts drive fulfilment; arrivals, releases and returns do not count as accepted quantity. ERP references are manual until an adapter is configured.'},
  {id:'access',title:'Prepare staff and site access',roles:['ADMIN'],route:'admin',before:'Confirm who is authorised to see this tenant and site.',action:'Create separate staff accounts in Administration. Check tenant modules, workflow version, site and role permissions.',expect:'Each person has their own role and site. Only Admin can switch working roles; switching does not create an independent reviewer.'},
  {id:'fleet',title:'Register vehicle, driver and rating evidence',roles:['ADMIN'],route:'admin',before:'Obtain fleet identifiers and manufacturer rating documents.',action:'Use fleet registration, then record rating evidence and a dated vehicle configuration in the evidence desk. Retain the original document separately.',expect:'Fleet records belong to the tenant. A file fingerprint identifies a document; it does not upload or verify it.'},
  {id:'review',title:'Independently review fleet evidence',roles:['COMPLIANCE_OFFICER','ADMIN'],route:'audit',before:'A different person authored the evidence and configuration.',action:'Open the evidence desk in Audit. Review the retained documents and record acceptance or rejection with a reason.',expect:'Evidence and configuration have separate review histories. Authors cannot approve their own records.'},
  {id:'trip',title:'Prepare route and trip',roles:['DISPATCH_SUPERVISOR','OPERATIONS_SUPERVISOR','FACILITY_MANAGER','ADMIN'],route:'routes',before:'Registered vehicle and driver; known origin, destination and waypoints.',action:'Preview the route, save the trip draft and select it. Record ERP references manually. After linking a visit, configure delivery stops and consignments before release.',expect:'The trip has an owned vehicle, driver and itinerary. Map geometry does not certify truck restrictions, statutory clearance or tracker connectivity.'},
  {id:'arrival',title:'Register and link the yard visit',roles:['DISPATCH_SUPERVISOR','OPERATIONS_SUPERVISOR'],route:'queue',before:'The truck has physically arrived at the selected site; its trip is prepared.',action:'Register arrival in Shift queue. In Routes, select the trip and link its matching visit. Operations can assign a dock.',expect:'One retained journey connects trip and origin visit. Assignment mismatches are blocked.'},
  {id:'context',title:'Complete inspection prerequisites',roles:['DISPATCH_SUPERVISOR','OPERATIONS_SUPERVISOR','FACILITY_MANAGER'],route:'compliance',before:'Select the visit; reviewed configuration and dispatched trip are available.',action:'Record or select the load, vehicle configuration, driver, trip and route/jurisdiction context. Follow each missing-prerequisite message.',expect:'CONFIGURATION_REQUIRED remains a hold until actual records and applicable rules exist. Readiness percentage cannot authorise release.'},
  {id:'inspect',title:'Inspect and obtain any independent approval',roles:['DISPATCH_SUPERVISOR','OPERATIONS_SUPERVISOR'],route:'compliance',before:'Complete context and a published applicable regulatory or tenant policy pack.',action:'Record measured weights and checklist observations, evaluate and read the retained decision. For eligible exceptions, request approval from a different authorised person.',expect:'Attempts retain inputs and rule versions. Tenant procedures remain distinct from law; checklist ticks cannot bypass missing or stale evidence.'},
  {id:'release',title:'Authorise release and observe physical exit',roles:['DISPATCH_SUPERVISOR','OPERATIONS_SUPERVISOR','FACILITY_MANAGER'],route:'queue',before:'Current inspection and any required approval authorise release.',action:'Release in Shift queue, then open the journey in Routes. Record dock vacancy if occupied, followed by physical gate exit.',expect:'Newly linked journeys separate release authority, dock vacancy and exit. Exit rechecks authority. Historical visits retain their original semantics.'},
  {id:'delivery',title:'Follow every destination and receipt',roles:['OPERATIONS_SUPERVISOR','FACILITY_MANAGER'],route:'routes',before:'Departure recorded; any multi-stop plan saved before release.',action:'At each ordered stop, record arrival and accepted or rejected delivery, receiver, evidence reference and fingerprint. Rejected deliveries can be retried at the same destination.',expect:'Intermediate acceptance does not complete the trip. Staff observations do not imply live tracking.'},
  {id:'returns',title:'Authorise and receive rejected consignments',roles:['OPERATIONS_SUPERVISOR','FACILITY_MANAGER'],route:'routes',before:'Active delivery rejected; return site within your access.',action:'Authorise the full rejected-stop return with receiving site and route evidence. Resolve remaining stops, record return transit, register a new receiving-yard visit, then record arrival and receipt.',expect:'Trip completion with returns requires resolved stops and received returns. ERP credit notes and commercial closure remain unconfirmed.'},
  {id:'recover',title:'Recover unused release authority',roles:['OPERATIONS_SUPERVISOR','FACILITY_MANAGER'],route:'routes',before:'Newly linked visit released; physical exit has not happened.',action:'Use Withdraw release for reinspection with a reason. Return to inspection and create a fresh attempt before a new release.',expect:'Old release and withdrawal remain visible. This does not reverse a physical departure or invent a return.'},
  {id:'oversight',title:'Check history and external reconciliation',roles:['FACILITY_MANAGER','COMPLIANCE_OFFICER','EXECUTIVE','ADMIN'],route:'audit',before:'Events recorded by their responsible owners.',action:'Inspect journey history, audit and permitted reports. Compare inspection, release and exit times. Ask the ERP owner to reconcile references and commercial closure.',expect:'Delivery evidence, ERP acknowledgement and commercial completion stay separate. Unconfigured adapters remain explicit.'},
]
