# Generated by Django 6.1.1 on 2026-10-07 09:36

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0005_refreshsession'),
        ('trip', '0009_organisation_requires_release'),
        ('yard', '0005_compliancecheck_submission_digest_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='JourneyLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.TextField()),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('assignment', models.JSONField()),
                ('external_system', models.CharField(blank=True, max_length=80)),
                ('external_reference', models.CharField(blank=True, max_length=120)),
                ('creator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('facility', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.facility')),
                ('organisation', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='trip.organisation')),
                ('trip', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='journey_link', to='trip.trip')),
                ('visit', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='journey_link', to='yard.queueentry')),
            ],
        ),
        migrations.CreateModel(
            name='JourneyEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.TextField()),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('kind', models.CharField(choices=[('DEPARTED', 'DEPARTED'), ('DESTINATION_ARRIVED', 'DESTINATION_ARRIVED'), ('DELIVERY_ACCEPTED', 'DELIVERY_ACCEPTED'), ('DELIVERY_REJECTED', 'DELIVERY_REJECTED')], max_length=30)),
                ('observed_at', models.DateTimeField()),
                ('details', models.JSONField(default=dict)),
                ('client_key', models.CharField(max_length=64)),
                ('creator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('organisation', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='trip.organisation')),
                ('journey', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='events', to='journeys.journeylink')),
            ],
        ),
        migrations.AddConstraint(
            model_name='journeylink',
            constraint=models.UniqueConstraint(condition=models.Q(('external_reference', ''), _negated=True), fields=('organisation', 'external_system', 'external_reference'), name='unique_journey_external_reference'),
        ),
        migrations.AddConstraint(
            model_name='journeyevent',
            constraint=models.UniqueConstraint(fields=('journey', 'client_key'), name='unique_journey_event_replay'),
        ),
    ]
