# Generated by Django 6.1.1 on 2026-10-07 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journeys', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='journeyevent',
            name='details',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
