# Generated by Django 6.1.1 on 2026-10-07 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journeys', '0002_alter_journeyevent_details'),
    ]

    operations = [
        migrations.AlterField(
            model_name='journeyevent',
            name='kind',
            field=models.CharField(choices=[('DOCK_VACATED', 'DOCK_VACATED'), ('DEPARTED', 'DEPARTED'), ('DESTINATION_ARRIVED', 'DESTINATION_ARRIVED'), ('DELIVERY_ACCEPTED', 'DELIVERY_ACCEPTED'), ('DELIVERY_REJECTED', 'DELIVERY_REJECTED'), ('DELIVERY_REATTEMPT_PLANNED', 'DELIVERY_REATTEMPT_PLANNED')], max_length=30),
        ),
    ]
