# Generated by Django 6.1.1 on 2026-10-07 11:19

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_refreshsession'),
        ('journeys', '0003_alter_journeyevent_kind'),
        ('trip', '0010_alter_trip_status'),
        ('yard', '0006_queueentry_dock_vacated_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='journeyevent',
            name='receiving_visit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='return_arrivals', to='yard.queueentry'),
        ),
        migrations.AddField(
            model_name='journeyevent',
            name='stop_index',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='journeyevent',
            name='kind',
            field=models.CharField(choices=[('DOCK_VACATED', 'DOCK_VACATED'), ('DEPARTED', 'DEPARTED'), ('DESTINATION_ARRIVED', 'DESTINATION_ARRIVED'), ('DELIVERY_ACCEPTED', 'DELIVERY_ACCEPTED'), ('DELIVERY_REJECTED', 'DELIVERY_REJECTED'), ('DELIVERY_REATTEMPT_PLANNED', 'DELIVERY_REATTEMPT_PLANNED'), ('RETURN_IN_TRANSIT', 'RETURN_IN_TRANSIT'), ('RETURN_ARRIVED', 'RETURN_ARRIVED'), ('RETURN_RECEIVED', 'RETURN_RECEIVED')], max_length=30),
        ),
        migrations.CreateModel(
            name='ReturnOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.TextField()),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('client_key', models.CharField(max_length=64)),
                ('route_reference', models.CharField(max_length=300)),
                ('route_sha256', models.CharField(max_length=64)),
                ('route_type', models.CharField(choices=[('DOMESTIC', 'Domestic'), ('CROSS_BORDER', 'Cross border')], max_length=20)),
                ('jurisdictions', models.JSONField()),
                ('consignments', models.JSONField(blank=True, default=list)),
                ('creator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('facility', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.facility')),
                ('journey', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='returns', to='journeys.journeylink')),
                ('organisation', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='trip.organisation')),
                ('rejection', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='authorised_return', to='journeys.journeyevent')),
            ],
        ),
        migrations.AddField(
            model_name='journeyevent',
            name='return_order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='events', to='journeys.returnorder'),
        ),
        migrations.CreateModel(
            name='DeliveryPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.TextField()),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('version', models.PositiveIntegerField()),
                ('client_key', models.CharField(max_length=64)),
                ('stops', models.JSONField()),
                ('creator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('journey', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='delivery_plans', to='journeys.journeylink')),
                ('organisation', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='trip.organisation')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('journey', 'version'), name='unique_delivery_plan_version'), models.UniqueConstraint(fields=('journey', 'client_key'), name='unique_delivery_plan_replay')],
            },
        ),
        migrations.AddConstraint(
            model_name='returnorder',
            constraint=models.UniqueConstraint(fields=('journey', 'client_key'), name='unique_return_order_replay'),
        ),
    ]
