# Generated by Django 6.1.1 on 2026-10-07 17:27

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_refreshsession'),
        ('journeys', '0004_journeyevent_receiving_visit_journeyevent_stop_index_and_more'),
        ('trip', '0010_alter_trip_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Consignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.TextField()),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('reference', models.CharField(max_length=120)),
                ('customer_name', models.CharField(max_length=200)),
                ('customer_reference', models.CharField(blank=True, max_length=120)),
                ('commodity', models.CharField(max_length=200)),
                ('target_quantity', models.DecimalField(decimal_places=3, max_digits=13)),
                ('unit', models.CharField(max_length=120)),
                ('deadline', models.DateField(blank=True, null=True)),
                ('external_system', models.CharField(blank=True, max_length=80)),
                ('external_reference', models.CharField(blank=True, max_length=120)),
                ('client_key', models.CharField(max_length=64)),
                ('creator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('facility', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.facility')),
                ('organisation', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='trip.organisation')),
            ],
        ),
        migrations.CreateModel(
            name='ConsignmentAllocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.TextField()),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('stop_index', models.PositiveSmallIntegerField()),
                ('reference', models.CharField(max_length=120)),
                ('quantity', models.DecimalField(decimal_places=3, max_digits=13)),
                ('client_key', models.CharField(max_length=64)),
                ('consignment', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='allocations', to='journeys.consignment')),
                ('creator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('organisation', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='trip.organisation')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='consignment_allocations', to='journeys.deliveryplan')),
            ],
        ),
        migrations.AddConstraint(
            model_name='consignment',
            constraint=models.UniqueConstraint(fields=('organisation', 'reference'), name='unique_tenant_consignment_reference'),
        ),
        migrations.AddConstraint(
            model_name='consignment',
            constraint=models.UniqueConstraint(fields=('organisation', 'client_key'), name='unique_consignment_replay'),
        ),
        migrations.AddConstraint(
            model_name='consignment',
            constraint=models.CheckConstraint(condition=models.Q(('target_quantity__gt', 0)), name='positive_consignment_target'),
        ),
        migrations.AddConstraint(
            model_name='consignmentallocation',
            constraint=models.UniqueConstraint(fields=('plan', 'reference'), name='unique_allocated_plan_line'),
        ),
        migrations.AddConstraint(
            model_name='consignmentallocation',
            constraint=models.UniqueConstraint(fields=('consignment', 'client_key'), name='unique_allocation_replay'),
        ),
        migrations.AddConstraint(
            model_name='consignmentallocation',
            constraint=models.CheckConstraint(condition=models.Q(('quantity__gt', 0)), name='positive_consignment_allocation'),
        ),
    ]
