# Generated by Django 6.1.1 on 2026-10-04 20:37

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        ('trip', '0007_userprofile_facilities_userprofile_role'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('action', models.CharField(max_length=100)),
                ('payload', models.TextField()),
                ('actor_ref', models.CharField(blank=True, default='', max_length=64)),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('previous_hash', models.CharField(default='', max_length=64)),
                ('hash', models.CharField(default='', max_length=64)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_entries', to=settings.AUTH_USER_MODEL)),
                ('facility', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audit_logs', to='core.facility')),
                ('organisation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audit_logs', to='trip.organisation')),
            ],
            options={
                'ordering': ['facility', 'timestamp'],
            },
        ),
        migrations.CreateModel(
            name='Dock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('AVAILABLE', 'Available'), ('OCCUPIED', 'Occupied'), ('MAINTENANCE', 'Maintenance')], default='AVAILABLE', max_length=16)),
                ('capacity_kg', models.FloatField(default=0.0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('facility', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='docks', to='core.facility')),
                ('organisation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='docks', to='trip.organisation')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='QueueEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reg_number', models.CharField(max_length=20)),
                ('driver_name', models.CharField(blank=True, default='', max_length=120)),
                ('haulier', models.CharField(blank=True, default='', max_length=120)),
                ('vehicle_type', models.CharField(blank=True, default='', max_length=50)),
                ('cargo_type', models.CharField(blank=True, default='', max_length=100)),
                ('status', models.CharField(choices=[('QUEUED', 'Queued'), ('ASSIGNED', 'Assigned'), ('AT_DOCK', 'At dock'), ('QUARANTINED', 'Quarantined'), ('PENDING_OVERRIDE', 'Pending override'), ('OVERRIDE_APPROVED', 'Override approved'), ('RELEASED', 'Released'), ('COMPLETED', 'Completed')], default='QUEUED', max_length=24)),
                ('entry_timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('exit_timestamp', models.DateTimeField(blank=True, null=True)),
                ('dwell_duration_seconds', models.BigIntegerField(blank=True, null=True)),
                ('idempotency_key', models.CharField(blank=True, default='', max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_dock', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='queue_entries', to='yard.dock')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='queue_entries_created', to=settings.AUTH_USER_MODEL)),
                ('facility', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='queue_entries', to='core.facility')),
                ('organisation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='queue_entries', to='trip.organisation')),
            ],
            options={
                'ordering': ['entry_timestamp'],
            },
        ),
        migrations.AddField(
            model_name='dock',
            name='current_entry',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='yard.queueentry'),
        ),
        migrations.CreateModel(
            name='ComplianceCheck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reg_number', models.CharField(max_length=20)),
                ('vehicle_type', models.CharField(default='DEFAULT', max_length=50)),
                ('route_type', models.CharField(default='DEFAULT', max_length=50)),
                ('axle_weights', models.JSONField(blank=True, default=list)),
                ('measured_total_kg', models.FloatField(default=0.0)),
                ('max_permissible_kg', models.FloatField(default=0.0)),
                ('overload_kg', models.FloatField(default=0.0)),
                ('overload_fee_usd', models.FloatField(default=0.0)),
                ('checklist_results', models.JSONField(blank=True, default=dict)),
                ('status', models.CharField(choices=[('PASSED', 'Passed'), ('QUARANTINED', 'Quarantined'), ('PENDING_OVERRIDE', 'Pending override'), ('OVERRIDE_APPROVED', 'Override approved')], default='PASSED', max_length=24)),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('override_reason', models.TextField(blank=True, default='')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('facility', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='compliance_checks', to='core.facility')),
                ('inspector', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='compliance_checks_inspected', to=settings.AUTH_USER_MODEL)),
                ('organisation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='compliance_checks', to='trip.organisation')),
                ('override_authorizer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='compliance_overrides_approved', to=settings.AUTH_USER_MODEL)),
                ('queue_entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='compliance_checks', to='yard.queueentry')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='Alert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('severity', models.CharField(choices=[('CRITICAL', 'Critical'), ('HIGH', 'High'), ('MEDIUM', 'Medium'), ('LOW', 'Low')], max_length=16)),
                ('message', models.TextField()),
                ('category', models.CharField(default='GENERAL', max_length=50)),
                ('acknowledged', models.BooleanField(default=False)),
                ('acknowledged_at', models.DateTimeField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('acknowledged_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alerts_acknowledged', to=settings.AUTH_USER_MODEL)),
                ('facility', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to='core.facility')),
                ('organisation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to='trip.organisation')),
            ],
            options={
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['facility', 'acknowledged'], name='idx_alert_facility_ack')],
            },
        ),
        migrations.CreateModel(
            name='ComplianceConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('route_type', models.CharField(default='DEFAULT', max_length=50)),
                ('vehicle_type', models.CharField(default='DEFAULT', max_length=50)),
                ('axle_limits', models.JSONField(blank=True, default=list)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organisation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='compliance_configs', to='trip.organisation')),
            ],
            options={
                'ordering': ['route_type', 'vehicle_type'],
                'constraints': [models.UniqueConstraint(fields=('organisation', 'route_type', 'vehicle_type'), name='unique_si_config_per_org_route_vehicle')],
            },
        ),
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('kind', models.CharField(choices=[('WEIGHBRIDGE', 'Weighbridge'), ('CRANE', 'Crane'), ('FORKLIFT', 'Forklift'), ('GENERATOR', 'Generator'), ('OTHER', 'Other')], default='OTHER', max_length=20)),
                ('status', models.CharField(choices=[('AVAILABLE', 'Available'), ('OCCUPIED', 'Occupied'), ('MAINTENANCE', 'Maintenance')], default='AVAILABLE', max_length=16)),
                ('notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('facility', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='equipment', to='core.facility')),
                ('organisation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='equipment', to='trip.organisation')),
            ],
            options={
                'ordering': ['name'],
                'constraints': [models.UniqueConstraint(fields=('facility', 'name'), name='unique_equipment_name_per_facility')],
            },
        ),
        migrations.AddIndex(
            model_name='queueentry',
            index=models.Index(fields=['facility', 'status'], name='idx_queue_facility_status'),
        ),
        migrations.AddIndex(
            model_name='queueentry',
            index=models.Index(fields=['facility', 'entry_timestamp'], name='idx_queue_facility_entry'),
        ),
        migrations.AddConstraint(
            model_name='queueentry',
            constraint=models.UniqueConstraint(condition=models.Q(('idempotency_key', ''), _negated=True), fields=('facility', 'idempotency_key'), name='unique_queue_idempotency_per_facility'),
        ),
        migrations.AddConstraint(
            model_name='dock',
            constraint=models.UniqueConstraint(fields=('facility', 'name'), name='unique_dock_name_per_facility'),
        ),
        migrations.AddIndex(
            model_name='compliancecheck',
            index=models.Index(fields=['facility', 'status'], name='idx_check_facility_status'),
        ),
    ]
