# Generated by Django 6.1.1 on 2026-10-04 22:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yard', '0002_compliancecheck_override_requester'),
    ]

    operations = [
        migrations.AddField(
            model_name='alert',
            name='related_queue_entry',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alerts', to='yard.queueentry'),
        ),
        migrations.AddField(
            model_name='queueentry',
            name='expected_destination',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
    ]
