# Generated by Django 6.1.1 on 2026-10-04 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yard', '0003_alert_related_queue_entry_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='compliancecheck',
            name='client_key',
            field=models.CharField(blank=True, db_index=True, default='', max_length=64),
        ),
    ]
