# Generated by Django 6.1.1 on 2026-10-05 19:21

from django.conf import settings
from django.db import migrations, models


def check_legacy_keys(apps, schema_editor):
    Check = apps.get_model('yard', 'ComplianceCheck')
    duplicates = (Check.objects.using(schema_editor.connection.alias).exclude(client_key='')
                  .values('facility_id', 'client_key').annotate(count=models.Count('pk'))
                  .filter(count__gt=1))
    if duplicates.exists():
        raise RuntimeError('Duplicate legacy inspection keys require reconciliation before this migration; no history was deleted')


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_pushsubscription'),
        ('trip', '0007_userprofile_facilities_userprofile_role'),
        ('yard', '0004_compliancecheck_client_key'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='compliancecheck',
            name='submission_digest',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.RunPython(check_legacy_keys, migrations.RunPython.noop),
        migrations.AddConstraint(
            model_name='compliancecheck',
            constraint=models.UniqueConstraint(condition=models.Q(('client_key', ''), _negated=True), fields=('facility', 'client_key'), name='unique_check_key_per_facility'),
        ),
    ]
