# Generated by Django 6.1.1 on 2026-10-07 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yard', '0005_compliancecheck_submission_digest_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='queueentry',
            name='dock_vacated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='queueentry',
            name='milestone_semantics',
            field=models.CharField(choices=[('LEGACY_COMBINED', 'Legacy combined release'), ('SEPARATE_V1', 'Separate yard milestones')], default='LEGACY_COMBINED', max_length=24),
        ),
        migrations.AddField(
            model_name='queueentry',
            name='release_authorized_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
