# Generated by Django 6.1.1 on 2026-10-07 12:41

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_refreshsession'),
        ('trip', '0010_alter_trip_status'),
        ('yard', '0006_queueentry_dock_vacated_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MovementOwnership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stage', models.CharField(choices=[('FLEET', 'FLEET'), ('TRIP', 'TRIP'), ('EVIDENCE', 'EVIDENCE'), ('SETUP', 'SETUP'), ('INSPECTION', 'INSPECTION'), ('APPROVAL', 'APPROVAL'), ('RELEASE', 'RELEASE'), ('EXIT', 'EXIT'), ('JOURNEY', 'JOURNEY')], max_length=24)),
                ('reason', models.TextField()),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movement_assignments', to=settings.AUTH_USER_MODEL)),
                ('facility', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.facility')),
                ('organisation', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='trip.organisation')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movement_responsibilities', to=settings.AUTH_USER_MODEL)),
                ('queue_entry', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ownerships', to='yard.queueentry')),
            ],
            options={
                'ordering': ['-created_at', '-pk'],
                'indexes': [models.Index(fields=['queue_entry', 'stage'], name='movement_owner_stage_idx')],
            },
        ),
    ]
