import { test, expect } from '@playwright/test'

test.use({ trace:'off' })
test('BAK is configured as a tenant and platform settings are readable without mutation', async ({ page, request }) => {
  test.skip(!process.env.BAK_ADMIN_PIN, 'Explicit admin credentials required')
  await page.goto('/')
  await page.getByLabel('Staff ID', { exact:true }).fill(process.env.BAK_ADMIN_STAFF_ID || 'TRK-BAK-ADMIN')
  await page.getByLabel('PIN', { exact:true }).fill(process.env.BAK_ADMIN_PIN!)
  await page.getByRole('button', { name:'Sign in to shift',exact:true }).click()
  await expect(page).toHaveURL(/\/reports$/)
  await expect(page.getByRole('banner')).toContainText('BAK Logistics')
  const api = process.env.PW_PROD_API_URL!
  const token = await page.evaluate(() => localStorage.getItem('trucki-auth-token'))
  const headers = { Authorization: `Token ${token}` }
  const identityResponse = await request.get(`${api}/api/auth/me/`, { headers })
  expect(identityResponse.ok()).toBe(true)
  const identity = (await identityResponse.json()).user
  expect(identity.id).toBe(2)
  expect(identity.organisation_id).toBe(1)
  expect(identity.facilities[0].id).toBe(1)
  expect(identity.tenant_configuration.version).toBe(1)
  expect(identity.tenant_configuration.content.branding.display_name).toBe('BAK Logistics')
  const configResponse = await request.get(`${api}/api/tenant/configuration/`, { headers })
  expect(configResponse.ok()).toBe(true)
  expect((await configResponse.json()).configuration.digest).toBe(identity.tenant_configuration.digest)
  const catalogue = await request.get(`${api}/api/regulatory/platform-catalogue/`, { headers })
  expect(catalogue.ok()).toBe(true)
  expect((await catalogue.json()).bundles).toEqual([])
  const selections = await request.get(`${api}/api/regulatory/tenant-selections/`, { headers })
  expect(selections.ok()).toBe(true)
  expect((await selections.json()).selections).toEqual([])
  await page.getByRole('link', { name:'Admin',exact:true }).click()
  await expect(page.getByLabel('Tenant display name')).toHaveValue('BAK Logistics')
  await expect(page.getByLabel('Maximum inspection age in seconds')).toHaveValue('3600')
  await expect(page.getByLabel('Mandatory inspection checks (one identifier per line)')).toHaveValue(/driver-license/)
  await expect(page.getByRole('button', { name:'Save tenant configuration' })).toBeVisible()
  await expect(page.getByRole('region',{name:'Modules and workflow releases'})).toBeVisible()
  await expect(page.getByText('Active release 1.',{exact:false})).toBeVisible()
  await expect(page.getByText('routing: enabled',{exact:true})).toBeVisible()
  const registry = await request.get(`${api}/api/tenant/registry/`,{headers})
  expect(registry.ok()).toBe(true)
  const release = (await registry.json()).release
  expect(release.version).toBe(1)
  const artifacts = await request.get(`${api}/api/tenant/revisions/`,{headers})
  expect(artifacts.ok()).toBe(true)
  const revisions = (await artifacts.json()).revisions
  expect(revisions.some((r:{kind:string;content:{classification?:string}}) => r.kind === 'POLICY' && r.content.classification === 'TENANT_POLICY')).toBe(true)
  const knowledge = await request.get(`${api}/api/regulatory/knowledge/`,{headers})
  expect(knowledge.ok()).toBe(true)
  expect((await knowledge.json()).revisions).toEqual([])
  await page.setViewportSize({ width:390,height:1000 })
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true)
  await page.screenshot({ path:'../docs/design/tenant-configuration-production-mobile.png',fullPage:true })
  await page.reload()
  await expect(page.getByLabel('Tenant display name')).toHaveValue('BAK Logistics')
  await page.getByRole('button', { name:'Sign out',exact:true }).click()
})
