import { test, expect } from '@playwright/test'
import { readFile } from 'node:fs/promises'
test.use({ trace: 'off' })
test('tenant modelling runs synthetic evaluation without operational writes', async ({ page }) => {
  test.skip(!process.env.BAK_ADMIN_PIN, 'Explicit tenant admin credentials required')
  await page.goto('/')
  await page.getByLabel('Staff ID', { exact: true }).fill(process.env.BAK_ADMIN_STAFF_ID || 'TRK-BAK-ADMIN')
  await page.getByLabel('PIN', { exact: true }).fill(process.env.BAK_ADMIN_PIN!)
  await page.getByRole('button', { name: 'Sign in to shift', exact: true }).click()
  await expect(page).toHaveURL(/\/reports$/)
  await expect(page.getByLabel('Selected yard')).toHaveValue('1')
  await page.getByRole('link', { name: 'Modelling', exact: true }).click()
  await page.getByRole('button', { name: 'Run synthetic model', exact: true }).click()
  await expect(page.getByText('7 of 7 expected decisions matched', { exact: false })).toBeVisible()
  // Existing critical yard alerts in the header are independent of model errors.
  await expect(page.getByRole('main').getByRole('alert')).toHaveCount(0)
  const downloaded = page.waitForEvent('download')
  await page.getByRole('button', { name: 'Export model evidence' }).click()
  const download = await downloaded
  const evidence = JSON.parse(await readFile((await download.path())!, 'utf8'))
  expect(evidence.synthetic).toBe(true)
  expect(evidence.verified_law).toBe(false)
  expect(evidence.scenarios).toHaveLength(7)
  expect(evidence.movements).toHaveLength(72)
  expect(evidence.scenarios[0].ruleset_snapshot).toHaveLength(1)
  expect(evidence.organisation.name).toBe('BAK Operations')
  expect(await page.locator('body').innerText()).not.toContain('—')
  await page.setViewportSize({ width: 1440, height: 1000 })
  await page.screenshot({ path: '../docs/design/tenant-model-desktop.png', fullPage: true })
  await page.setViewportSize({ width: 390, height: 844 })
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true)
  await page.screenshot({ path: '../docs/design/tenant-model-mobile.png', fullPage: true })
  await page.getByRole('button', { name: 'Sign out', exact: true }).click()
})
