# Generated by Django 6.1.1 on 2026-10-06 09:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trip', '0008_trip_facility_trip_route_client_key_and_more'),
        ('whatsapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='whatsappsession',
            name='organisation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='trip.organisation'),
        ),
        migrations.AlterField(
            model_name='whatsappsession',
            name='phone_number',
            field=models.CharField(max_length=30),
        ),
        migrations.AddConstraint(
            model_name='whatsappsession',
            constraint=models.UniqueConstraint(fields=('organisation', 'phone_number'), name='unique_tenant_whatsapp_phone'),
        ),
        migrations.AddConstraint(
            model_name='whatsappsession',
            constraint=models.UniqueConstraint(condition=models.Q(('organisation__isnull', True)), fields=('phone_number',), name='unique_legacy_whatsapp_phone'),
        ),
    ]
