import {Link} from 'react-router-dom'
import {useLive} from '../lib/liveGate'
import {canVisit,type RouteKey} from '../lib/gates'
import {WALKTHROUGH_ROLES} from '../lib/walkthrough'
import {useSession} from '../store/session'
import {PageHeader,Section} from '../components/ui'
export default function Hub(){
  const live=useLive();const role=useSession(s=>s.role)
  const screens:[string,RouteKey,string][]=[['Shift queue','queue','Arrivals, inspection handoffs and authorised release.'],['Inspection','compliance','Context, observations, versioned evaluation and approval.'],['Dock board','docks','Dock assignment and occupancy.'],['Routes and journeys','routes','Trip drafts, linked visits, movement, delivery stops and returns.'],['Reports','reports','Performance and CSV export.'],['Audit','audit','Retained actions and integrity verification.'],['Administration','admin','Tenant configuration, staff, fleet and evidence.']]
  return <div className="max-w-3xl space-y-4"><PageHeader title="Information hub" sub="Platform boundaries, responsibilities and practical help." mode={live?'live':'demo'}/>
    <Section title="Where Trucki fits" sub="Transport operations alongside your existing systems"><p className="text-sm">Trucki connects yard visits, inspection evidence, release decisions and journey handoffs. Tenants own fleet and operational records; reusable regulatory capabilities belong to the platform. ERP/WMS and fleet tracking connections require configured adapters and agreed ownership.</p><Link to="/guide" className="btn-primary mt-3 inline-block px-4">Start the operational walkthrough</Link></Section>
    <Section title="Evidence and authority" sub="Readiness is not permission to leave"><p className="text-sm">Decisions retain source revisions, effective dates, inputs and rule versions. Tenant procedures are internal policies, never statutory law. No instrument or monetary penalty is asserted as verified law by this walkthrough. Missing, expired or unreviewed prerequisites remain visible and can block release.</p></Section>
    <Section title="Who does what" sub="Your working role and tenant permissions control actions"><ul className="space-y-2">{WALKTHROUGH_ROLES.map(r=><li key={r.role} className="card p-3 text-sm"><strong>{r.role.replaceAll('_',' ')}</strong><p>{r.purpose}</p></li>)}</ul></Section>
    <Section title="When a step is blocked" sub="Resolve the cause with its responsible owner"><ul className="list-disc space-y-2 pl-5 text-sm"><li>Missing context: open the visit inspection and follow prerequisite messages. Fleet, dispatch or evidence owners must supply actual records.</li><li>Held inspection: read the recorded decision. Eligible exceptions require independent approval; approval does not erase a failed attempt.</li><li>Connection unavailable: supported arrivals can queue locally. Evidence, release and journey commands require connectivity and current server authority.</li><li>Access denied: check site and working role with your administrator. Each reviewer needs their own account and private PIN.</li><li>Instructions change before exit: Operations can withdraw unused release authority for reinspection. After departure, record actual delivery exceptions and authorised returns.</li><li>Tracker or ERP absent: manual references and staff observations do not prove an integration. Commercial reconciliation remains with the ERP owner.</li></ul></Section>
    <Section title="Your available screens" sub="Links respect current role and tenant modules"><ul className="space-y-2">{screens.filter(([,route])=>canVisit(route,role)).map(([title,route,detail])=><li className="card p-3 text-sm" key={route}><Link className="font-bold underline" to={`/${route}`}>{title}</Link><p>{detail}</p></li>)}</ul></Section>
  </div>
}
