import { useEffect, useState } from 'react'
import { Link } from 'react-router-dom'
import { canRetryPendingAction, listPendingActions, listRecoveryRecords, ownsPendingAction, retryPendingAction, type PendingAction, type RecoveryRecord } from '../lib/offline/db'
import { useLive } from '../lib/liveGate'
import { PageHeader, Section } from '../components/ui'

export default function Recovery(){
  const live=useLive();const [actions,setActions]=useState<PendingAction[]|null>(null);const [history,setHistory]=useState<RecoveryRecord[]>([])
  const [error,setError]=useState('');const [notice,setNotice]=useState('');const [busy,setBusy]=useState(false);const [reasons,setReasons]=useState<Record<string,string>>({});const [revision,setRevision]=useState(0)
  useEffect(()=>{let active=true;const load=async()=>{try{const rows=(await listPendingActions()).filter(ownsPendingAction);const records=await listRecoveryRecords();if(active){setActions(rows);setHistory(records);setError('')}}catch(e){if(active)setError(`Could not read local recovery records. ${(e as Error).message}`)}};void load();const timer=setInterval(()=>void load(),5000);return()=>{active=false;clearInterval(timer)}},[revision])
  async function retry(action:PendingAction){setBusy(true);setError('');setNotice('');try{await retryPendingAction(action.id,reasons[action.id]??'');const result=await(await import('../lib/live')).flushPendingActions();setNotice(`Retry queued with its original submission key. Replay completed ${result.done}; failed ${result.failed}. Review the current status below.`);setRevision(v=>v+1)}catch(e){setError((e as Error).message)}finally{setBusy(false)}}
  function download(){if(!actions)return;const blob=new Blob([JSON.stringify({exported_at:new Date().toISOString(),scope:'This staff identity, selected yard and backend on this device',pending:actions,recovery_history:history},null,2)],{type:'application/json'});const url=URL.createObjectURL(blob);const link=document.createElement('a');link.href=url;link.download='trucki-local-recovery.json';link.click();setTimeout(()=>URL.revokeObjectURL(url),1000)}
  return <div className="max-w-5xl space-y-5"><PageHeader title="Offline recovery" sub="Review saved submissions belonging to your current account and yard on this device." mode={live?'live':'demo'}/>
    <div className="flex flex-wrap gap-3"><button className="report-text-link" onClick={()=>setRevision(v=>v+1)}>Refresh local submissions</button><button className="route-mode-button min-h-12" disabled={!actions||busy} onClick={download}>Export recovery record</button><Link className="report-text-link" to="/dispatch">Open Dispatch flow</Link></div>
    {error&&<p role="alert" className="rounded-xl bg-red-50 p-4 text-red-800">{error} <button className="underline" onClick={()=>setRevision(v=>v+1)}>Retry</button></p>}{notice&&<p role="status" className="rounded-xl bg-slate-100 p-4 text-sm">{notice}</p>}
    <Section title="Saved submissions">{actions===null&&!error?<p role="status">Loading saved submissions…</p>:actions&&<><p className="mb-4 text-sm">{actions.filter(a=>a.state==='BLOCKED').length} need review · {actions.filter(a=>a.state!=='BLOCKED').length} awaiting replay. Records from other accounts, yards or backends are excluded.</p>{actions.length===0?<p>No saved submissions for this account and yard on this device.</p>:<ul className="space-y-4">{actions.map(action=><li key={action.id} className="rounded-xl border border-slate-200 p-4"><div className="flex flex-wrap justify-between gap-2"><h3 className="font-bold">{String(action.payload.licensePlate??action.payload.queueEntryId??'Saved submission')}</h3><span className={`rounded-lg px-3 py-1 text-sm font-bold ${action.state==='BLOCKED'?'bg-red-50 text-red-800':'bg-amber-50 text-amber-900'}`}>{action.state==='BLOCKED'?'Needs review':'Awaiting replay'}</span></div><p className="mt-2 text-sm">Captured {new Date(action.timestamp).toLocaleString()} · Failed attempts: {action.retryCount}</p><p className="mt-2 break-words text-sm">{action.lastError??'Waiting for a connection and authorised server acceptance.'}</p><details className="mt-2 text-sm"><summary className="min-h-11 cursor-pointer py-2">Submission details</summary><p className="break-all">Key: {action.id}</p><p>Action: {action.actionType}</p><pre className="mt-2 whitespace-pre-wrap break-all">{JSON.stringify(action.payload,null,2)}</pre></details>{canRetryPendingAction(action)?<div className="mt-3"><label className="text-sm">Retry reason<input className="field mt-1 block w-full" maxLength={1000} value={reasons[action.id]??''} onChange={e=>setReasons(old=>({...old,[action.id]:e.target.value}))}/></label><button className="btn-primary mt-3 min-h-12 px-4" disabled={busy||!navigator.onLine||!reasons[action.id]?.trim()} onClick={()=>void retry(action)}>Retry original submission</button></div>:action.state==='BLOCKED'?<p className="mt-3 text-sm font-semibold">Manual reconciliation required. Check the server movement with the site supervisor before capturing another arrival. Rejected or unknown submissions stay retained here.</p>:<p className="mt-3 text-sm">Automatic replay resumes when connected. Server permissions still apply.</p>}</li>)}</ul>}</>}</Section>
    <details className="card p-5"><summary className="min-h-11 cursor-pointer py-2 font-bold">Recovery history on this device ({history.length})</summary><ul className="mt-3 space-y-3">{history.map(record=><li key={record.id} className="break-words border-t pt-3 text-sm"><p>{new Date(record.at).toLocaleString()} · {record.reason}</p><p className="break-all">Submission {record.actionId}</p><p>Prior attempts: {record.priorRetryCount} · {record.priorError}</p></li>)}</ul></details>
    <p className="text-sm text-slate-600">Recovery records are stored on this device. Export them before clearing browser storage. Versioned inspections, approvals and gate release require a server connection.</p>
  </div>
}
