# Generated by Django 6.1.1 on 2026-10-05 20:01

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0002_pushsubscription'),
        ('trip', '0007_userprofile_facilities_userprofile_role'),
        ('yard', '0005_compliancecheck_submission_digest_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EvidenceRevision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('evidence_key', models.CharField(max_length=100)),
                ('revision', models.PositiveIntegerField()),
                ('kind', models.CharField(max_length=64)),
                ('issuer', models.CharField(max_length=200)),
                ('document_ref', models.CharField(max_length=500)),
                ('document_sha256', models.CharField(max_length=64)),
                ('issued_at', models.DateTimeField()),
                ('expires_at', models.DateTimeField()),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('driver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='trip.driver')),
                ('organisation', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='trip.organisation')),
                ('trip', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='trip.trip')),
                ('vehicle', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='trip.vehicle')),
            ],
        ),
        migrations.CreateModel(
            name='ContextEvidence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('organisation', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='trip.organisation')),
                ('evidence', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='regulatory.evidencerevision')),
            ],
        ),
        migrations.CreateModel(
            name='Load',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('reference', models.CharField(max_length=100)),
                ('cargo_class', models.CharField(max_length=64)),
                ('description', models.TextField(blank=True)),
                ('declared_mass_kg', models.DecimalField(decimal_places=3, max_digits=12)),
                ('dimensions_mm', models.JSONField(blank=True, default=dict)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('organisation', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='trip.organisation')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='evidencerevision',
            name='load',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='regulatory.load'),
        ),
        migrations.CreateModel(
            name='OperationalContext',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('route_type', models.CharField(choices=[('DOMESTIC', 'DOMESTIC'), ('CROSS_BORDER', 'CROSS_BORDER'), ('ABNORMAL', 'ABNORMAL')], max_length=24)),
                ('jurisdictions', models.JSONField()),
                ('origin', models.CharField(max_length=200)),
                ('destination', models.CharField(max_length=200)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='trip.driver')),
                ('evidence', models.ManyToManyField(through='regulatory.ContextEvidence', to='regulatory.evidencerevision')),
                ('load', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='regulatory.load')),
                ('organisation', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='trip.organisation')),
                ('queue_entry', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='regulatory_contexts', to='yard.queueentry')),
                ('trip', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='trip.trip')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='InspectionAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('client_key', models.CharField(blank=True, max_length=64)),
                ('submission_digest', models.CharField(max_length=64)),
                ('occurred_at', models.DateTimeField()),
                ('input_snapshot', models.JSONField()),
                ('context_snapshot', models.JSONField(default=dict)),
                ('ruleset_snapshot', models.JSONField(default=list)),
                ('result', models.JSONField()),
                ('decision', models.CharField(max_length=24)),
                ('engine_version', models.CharField(default='nrok-1', max_length=24)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('facility', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.facility')),
                ('organisation', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='trip.organisation')),
                ('queue_entry', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='inspection_attempts', to='yard.queueentry')),
                ('context', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='regulatory.operationalcontext')),
            ],
            options={
                'ordering': ['-created_at', '-pk'],
            },
        ),
        migrations.AddField(
            model_name='contextevidence',
            name='context',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='regulatory.operationalcontext'),
        ),
        migrations.CreateModel(
            name='OverrideRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('reason', models.TextField()),
                ('attempt', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='override_requests', to='regulatory.inspectionattempt')),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('organisation', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='trip.organisation')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='OverrideApproval',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('approved', models.BooleanField()),
                ('reason', models.TextField()),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('organisation', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='trip.organisation')),
                ('request', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='approval', to='regulatory.overriderequest')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ReleaseRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('policy_version', models.CharField(default='gate-1', max_length=24)),
                ('approval', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='regulatory.overrideapproval')),
                ('attempt', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='regulatory.inspectionattempt')),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('organisation', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='trip.organisation')),
                ('queue_entry', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='yard.queueentry')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='RuleSetVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('name', models.CharField(max_length=100)),
                ('version', models.PositiveIntegerField()),
                ('jurisdiction', models.CharField(max_length=32)),
                ('route_type', models.CharField(choices=[('DOMESTIC', 'DOMESTIC'), ('CROSS_BORDER', 'CROSS_BORDER'), ('ABNORMAL', 'ABNORMAL')], max_length=24)),
                ('effective_from', models.DateField()),
                ('effective_to', models.DateField()),
                ('max_age_seconds', models.PositiveIntegerField(default=3600)),
                ('content', models.JSONField()),
                ('digest', models.CharField(max_length=64)),
                ('schema_version', models.PositiveIntegerField(default=1)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('organisation', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='trip.organisation')),
            ],
        ),
        migrations.CreateModel(
            name='Publication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('reason', models.TextField()),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('organisation', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='trip.organisation')),
                ('ruleset', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='publication', to='regulatory.rulesetversion')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='RuleUnit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('rule_key', models.CharField(max_length=100)),
                ('revision', models.PositiveIntegerField()),
                ('definition', models.JSONField()),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('organisation', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='trip.organisation')),
            ],
        ),
        migrations.CreateModel(
            name='RuleSetMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('organisation', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='trip.organisation')),
                ('ruleset', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='members', to='regulatory.rulesetversion')),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='regulatory.ruleunit')),
            ],
        ),
        migrations.CreateModel(
            name='SourceRevision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('source_key', models.CharField(max_length=100)),
                ('revision', models.PositiveIntegerField()),
                ('title', models.CharField(max_length=250)),
                ('authority', models.CharField(max_length=200)),
                ('jurisdiction', models.CharField(max_length=32)),
                ('kind', models.CharField(choices=[('STATUTE', 'STATUTE'), ('INTERNAL_POLICY', 'INTERNAL_POLICY'), ('MANUFACTURER', 'MANUFACTURER')], max_length=24)),
                ('tier', models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D')], max_length=1)),
                ('provision', models.CharField(max_length=200)),
                ('document_ref', models.CharField(max_length=500)),
                ('document_sha256', models.CharField(max_length=64)),
                ('published_on', models.DateField()),
                ('effective_from', models.DateField()),
                ('effective_to', models.DateField(blank=True, null=True)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('organisation', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='trip.organisation')),
                ('supersedes', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='regulatory.sourcerevision')),
            ],
        ),
        migrations.AddField(
            model_name='ruleunit',
            name='source',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='regulatory.sourcerevision'),
        ),
        migrations.CreateModel(
            name='VehicleConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('revision', models.PositiveIntegerField()),
                ('vehicle_class', models.CharField(max_length=64)),
                ('axle_layout', models.JSONField()),
                ('rated_axle_kg', models.JSONField()),
                ('rated_gross_kg', models.DecimalField(decimal_places=3, max_digits=12)),
                ('effective_from', models.DateField()),
                ('effective_to', models.DateField(blank=True, null=True)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('organisation', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='trip.organisation')),
                ('rating_evidence', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='regulatory.evidencerevision')),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='trip.vehicle')),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('approved', models.BooleanField()),
                ('reason', models.TextField()),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('evidence', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='regulatory.evidencerevision')),
                ('organisation', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='trip.organisation')),
                ('source', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='regulatory.sourcerevision')),
                ('configuration', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='regulatory.vehicleconfiguration')),
            ],
        ),
        migrations.AddField(
            model_name='operationalcontext',
            name='configuration',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='regulatory.vehicleconfiguration'),
        ),
        migrations.AddConstraint(
            model_name='evidencerevision',
            constraint=models.UniqueConstraint(fields=('organisation', 'evidence_key', 'revision'), name='unique_evidence_revision'),
        ),
        migrations.AddConstraint(
            model_name='inspectionattempt',
            constraint=models.UniqueConstraint(condition=models.Q(('client_key', ''), _negated=True), fields=('facility', 'client_key'), name='unique_attempt_replay_per_site'),
        ),
        migrations.AddConstraint(
            model_name='contextevidence',
            constraint=models.UniqueConstraint(fields=('context', 'evidence'), name='unique_context_evidence'),
        ),
        migrations.AddConstraint(
            model_name='rulesetversion',
            constraint=models.UniqueConstraint(fields=('organisation', 'name', 'version'), name='unique_ruleset_version'),
        ),
        migrations.AddConstraint(
            model_name='rulesetmember',
            constraint=models.UniqueConstraint(fields=('ruleset', 'unit'), name='unique_ruleset_member'),
        ),
        migrations.AddConstraint(
            model_name='sourcerevision',
            constraint=models.UniqueConstraint(fields=('organisation', 'source_key', 'revision'), name='unique_reg_source_revision'),
        ),
        migrations.AddConstraint(
            model_name='ruleunit',
            constraint=models.UniqueConstraint(fields=('organisation', 'rule_key', 'revision'), name='unique_rule_unit_revision'),
        ),
        migrations.AddConstraint(
            model_name='vehicleconfiguration',
            constraint=models.UniqueConstraint(fields=('vehicle', 'revision'), name='unique_vehicle_config_revision'),
        ),
        migrations.AddConstraint(
            model_name='review',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('configuration__isnull', True), ('evidence__isnull', True), ('source__isnull', False)), models.Q(('configuration__isnull', True), ('evidence__isnull', False), ('source__isnull', True)), models.Q(('configuration__isnull', False), ('evidence__isnull', True), ('source__isnull', True)), _connector='OR'), name='one_review_subject'),
        ),
    ]
