# Generated by Django 6.1.1 on 2026-10-05 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('regulatory', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inspectionattempt',
            name='context_snapshot',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='inspectionattempt',
            name='ruleset_snapshot',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
