# Generated by Django 6.1.1 on 2026-10-06 08:54

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('regulatory', '0002_alter_inspectionattempt_context_snapshot_and_more'),
        ('trip', '0008_trip_facility_trip_route_client_key_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PlatformRuleBundle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.JSONField()),
                ('digest', models.CharField(max_length=64)),
                ('reason', models.TextField()),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('origin', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='regulatory.rulesetversion')),
            ],
        ),
        migrations.CreateModel(
            name='TenantRuleSelection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('jurisdiction', models.CharField(max_length=32)),
                ('route_type', models.CharField(max_length=24)),
                ('version', models.PositiveIntegerField()),
                ('reason', models.TextField()),
                ('bundle', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='regulatory.platformrulebundle')),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('organisation', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='trip.organisation')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('organisation', 'jurisdiction', 'route_type', 'version'), name='unique_tenant_rule_selection')],
            },
        ),
    ]
