# Generated by Django 6.1.1 on 2026-10-06 10:43

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('regulatory', '0003_platformrulebundle_tenantruleselection'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='inspectionattempt',
            name='tenant_configuration_snapshot',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.CreateModel(
            name='KnowledgeRevision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.TextField()),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('kind', models.CharField(choices=[('SOURCE', 'SOURCE'), ('ROU', 'ROU'), ('PACK', 'PACK')], max_length=12)),
                ('key', models.SlugField(max_length=100)),
                ('version', models.PositiveIntegerField()),
                ('content', models.JSONField()),
                ('digest', models.CharField(max_length=64)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='KnowledgeReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.TextField()),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('approved', models.BooleanField()),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('revision', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reviews', to='regulatory.knowledgerevision')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='GovernanceEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.TextField()),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('action', models.CharField(max_length=24)),
                ('previous_hash', models.CharField(max_length=64, unique=True)),
                ('hash', models.CharField(max_length=64, unique=True)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('revision', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='regulatory.knowledgerevision')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='LegacyKnowledgeMap',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.TextField()),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('legacy_kind', models.CharField(max_length=12)),
                ('legacy_id', models.PositiveIntegerField()),
                ('legacy_digest', models.CharField(max_length=64)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('revision', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='regulatory.knowledgerevision')),
            ],
        ),
        migrations.AddConstraint(
            model_name='knowledgerevision',
            constraint=models.UniqueConstraint(fields=('kind', 'key', 'version'), name='unique_platform_knowledge_version'),
        ),
        migrations.AddConstraint(
            model_name='legacyknowledgemap',
            constraint=models.UniqueConstraint(fields=('legacy_kind', 'legacy_id'), name='unique_legacy_knowledge_mapping'),
        ),
    ]
