# Generated by Django 6.1.1 on 2026-10-07 11:19

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('regulatory', '0004_inspectionattempt_tenant_configuration_snapshot_and_more'),
        ('trip', '0010_alter_trip_status'),
        ('yard', '0006_queueentry_dock_vacated_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='releaserecord',
            name='queue_entry',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='release_records', to='yard.queueentry'),
        ),
        migrations.CreateModel(
            name='ReleaseWithdrawal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('reason', models.TextField()),
                ('client_key', models.CharField(max_length=64)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('organisation', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='trip.organisation')),
                ('release', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='withdrawal', to='regulatory.releaserecord')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('organisation', 'client_key'), name='unique_release_withdrawal_key')],
            },
        ),
    ]
