# Generated by Django 6.1.1 on 2026-10-06 06:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authtoken', '0004_alter_tokenproxy_options'),
        ('core', '0002_pushsubscription'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminRoleSelection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('DISPATCH_SUPERVISOR', 'Dispatch Supervisor'), ('FACILITY_MANAGER', 'Facility Manager'), ('OPERATIONS_SUPERVISOR', 'Operations Supervisor'), ('EXECUTIVE', 'Executive'), ('ADMIN', 'Admin'), ('COMPLIANCE_OFFICER', 'Compliance Officer')], max_length=32)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('token', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='authtoken.token')),
            ],
        ),
    ]
