# Generated by Django 6.1.1 on 2026-10-06 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_adminroleselection'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facility',
            name='timezone',
            field=models.CharField(default='UTC', max_length=64),
        ),
    ]
