import {useEffect,useState} from 'react'
import {apiFetch} from '../lib/api'
import {useSession} from '../store/session'
type Ownership={stage:string;assignment_id:number|null;owner_id:number|null;candidates:{id:number;label:string;role:string}[]}
export default function MovementOwner({entryId,stage,assignmentId,onChanged,defaultOpen=false}:{entryId:number;stage:string;assignmentId:number|null|undefined;onChanged:()=>void;defaultOpen?:boolean}){
  const role=useSession(s=>s.role);const permitted=['ADMIN','OPERATIONS_SUPERVISOR','FACILITY_MANAGER'].includes(role??'')
  const [data,setData]=useState<Ownership|null>(null);const [owner,setOwner]=useState('');const [reason,setReason]=useState('');const [error,setError]=useState('');const [busy,setBusy]=useState(false);const [retry,setRetry]=useState(0)
  useEffect(()=>{if(!permitted)return;let active=true;apiFetch<Ownership>(`/operations/${entryId}/owner/`).then(d=>{if(!Array.isArray(d.candidates))throw Error('Eligible staff could not be loaded.');if(active){setData(d);setOwner(d.owner_id?String(d.owner_id):'');setError('')}}).catch(e=>{if(active)setError(e.message)});return()=>{active=false}},[entryId,stage,assignmentId,permitted,retry])
  if(!permitted)return null
  async function assign(){if(!data)return;setBusy(true);try{await apiFetch(`/operations/${entryId}/owner/`,{method:'POST',body:{stage:data.stage,expected_assignment_id:data.assignment_id,owner_id:Number(owner),reason}});setReason('');setRetry(n=>n+1);onChanged()}catch(e){setError((e as Error).message)}finally{setBusy(false)}}
  return <details className="mt-3 border-t pt-3" open={defaultOpen}><summary className="cursor-pointer text-sm font-bold">Assign the next handoff owner</summary>{error?<p role="alert">{error} <button onClick={()=>setRetry(n=>n+1)}>Retry</button></p>:!data?<p role="status">Loading eligible site staff…</p>:!data.candidates.length?<p className="mt-2 text-sm">No active staff in the responsible roles are assigned to this site. Admin must provision the appropriate staff account.</p>:<div className="mt-3 grid gap-3 sm:grid-cols-2"><label className="text-sm">Responsible staff member<select className="field mt-1 w-full" value={owner} onChange={e=>setOwner(e.target.value)}><option value="">Choose eligible site staff</option>{data.candidates.map(u=><option key={u.id} value={u.id}>{u.label} / {u.role.replaceAll('_',' ')}</option>)}</select></label><label className="text-sm">Handoff assignment reason<input className="field mt-1 w-full px-3" value={reason} onChange={e=>setReason(e.target.value)}/></label><button className="btn-secondary px-3" disabled={busy||!owner||!reason.trim()} onClick={()=>void assign()}>Assign accountable owner</button><p className="text-xs">Ownership is retained by stage. It grants no additional permissions and never permits self-approval.</p></div>}</details>
}
