# Generated by Django 6.1.1 on 2026-10-04 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        ('trip', '0006_trip_booking_reference_trip_booking_time_preference_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='facilities',
            field=models.ManyToManyField(blank=True, related_name='members', to='core.facility'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('DISPATCH_SUPERVISOR', 'Dispatch Supervisor'), ('FACILITY_MANAGER', 'Facility Manager'), ('OPERATIONS_SUPERVISOR', 'Operations Supervisor'), ('EXECUTIVE', 'Executive'), ('ADMIN', 'Admin'), ('COMPLIANCE_OFFICER', 'Compliance Officer')], default='OPERATIONS_SUPERVISOR', max_length=32),
        ),
    ]
