# Generated by Django 6.1.1 on 2026-10-06 08:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_adminroleselection'),
        ('trip', '0007_userprofile_facilities_userprofile_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='facility',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='trips', to='core.facility'),
        ),
        migrations.AddField(
            model_name='trip',
            name='route_client_key',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AddField(
            model_name='trip',
            name='routing_snapshot',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddConstraint(
            model_name='trip',
            constraint=models.UniqueConstraint(condition=models.Q(('route_client_key', ''), _negated=True), fields=('facility', 'route_client_key'), name='unique_route_draft_per_yard'),
        ),
    ]
