# Generated by Django 6.1.1 on 2026-10-06 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trip', '0008_trip_facility_trip_route_client_key_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='organisation',
            name='requires_release',
            field=models.BooleanField(default=False),
        ),
    ]
