# Generated by Django 6.1.1 on 2026-10-07 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trip', '0009_organisation_requires_release'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trip',
            name='status',
            field=models.CharField(choices=[('inquiry', 'Inquiry'), ('quoted', 'Quoted'), ('confirmed', 'Confirmed'), ('assigned', 'Assigned'), ('dispatched', 'Dispatched'), ('at_border', 'At Border'), ('in_transit', 'In Transit'), ('delivered', 'Delivered'), ('returned', 'Completed with returns'), ('paid', 'Paid'), ('cancelled', 'Cancelled')], default='inquiry', max_length=20),
        ),
    ]
