# Generated by Django 6.1.1 on 2026-10-06 08:53

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('trip', '0008_trip_facility_trip_route_client_key_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TenantConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.PositiveIntegerField()),
                ('content', models.JSONField()),
                ('digest', models.CharField(max_length=64)),
                ('effective_from', models.DateTimeField(default=django.utils.timezone.now)),
                ('reason', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('creator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('organisation', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='configuration_revisions', to='trip.organisation')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('organisation', 'version'), name='unique_tenant_config_version')],
            },
        ),
    ]
