# Generated by Django 6.1.1 on 2026-10-06 10:43

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_facility_timezone'),
        ('tenancy', '0002_bak_reference'),
        ('trip', '0008_trip_facility_trip_route_client_key_and_more'),
        ('yard', '0005_compliancecheck_submission_digest_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TenantArtifactRevision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.TextField()),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('kind', models.CharField(max_length=24)),
                ('key', models.SlugField(max_length=100)),
                ('version', models.PositiveIntegerField()),
                ('content', models.JSONField()),
                ('digest', models.CharField(max_length=64)),
                ('effective_from', models.DateTimeField(default=django.utils.timezone.now)),
                ('effective_to', models.DateTimeField(blank=True, null=True)),
                ('creator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('facility', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='core.facility')),
                ('organisation', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='trip.organisation')),
            ],
        ),
        migrations.CreateModel(
            name='ArtifactReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.TextField()),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('approved', models.BooleanField()),
                ('creator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('organisation', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='trip.organisation')),
                ('artifact', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tenancy.tenantartifactrevision')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TenantReleaseVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.TextField()),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('version', models.PositiveIntegerField()),
                ('artifact_ids', models.JSONField()),
                ('digest', models.CharField(max_length=64)),
                ('effective_from', models.DateTimeField(default=django.utils.timezone.now)),
                ('compatibility', models.BooleanField(default=False)),
                ('configuration', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tenancy.tenantconfiguration')),
                ('creator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('organisation', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='trip.organisation')),
            ],
        ),
        migrations.CreateModel(
            name='ReleaseActivation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.TextField()),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('version', models.PositiveIntegerField()),
                ('effective_from', models.DateTimeField(default=django.utils.timezone.now)),
                ('creator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('organisation', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='trip.organisation')),
                ('release', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tenancy.tenantreleaseversion')),
            ],
        ),
        migrations.CreateModel(
            name='WorkflowExecution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.TextField()),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('configuration_snapshot', models.JSONField()),
                ('creator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('facility', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.facility')),
                ('organisation', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='trip.organisation')),
                ('queue_entry', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='yard.queueentry')),
                ('release', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tenancy.tenantreleaseversion')),
                ('workflow', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tenancy.tenantartifactrevision')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='WorkflowEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.TextField()),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('transition', models.CharField(max_length=32)),
                ('state', models.CharField(max_length=32)),
                ('configuration_snapshot', models.JSONField()),
                ('audit', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='yard.auditlog')),
                ('creator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('organisation', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='trip.organisation')),
                ('execution', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='events', to='tenancy.workflowexecution')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddConstraint(
            model_name='tenantartifactrevision',
            constraint=models.UniqueConstraint(fields=('organisation', 'kind', 'key', 'version'), name='unique_tenant_artifact_version'),
        ),
        migrations.AddConstraint(
            model_name='tenantreleaseversion',
            constraint=models.UniqueConstraint(fields=('organisation', 'version'), name='unique_tenant_release_version'),
        ),
        migrations.AddConstraint(
            model_name='releaseactivation',
            constraint=models.UniqueConstraint(fields=('organisation', 'version'), name='unique_tenant_activation_version'),
        ),
    ]
