# Generated by Django 6.1.1 on 2026-10-08 06:51

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenancy', '0004_bak_compatibility_release'),
        ('trip', '0010_alter_trip_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TenantEntitlementVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.PositiveIntegerField()),
                ('modules', models.JSONField()),
                ('state', models.CharField(choices=[('ACTIVE', 'Active'), ('SUSPENDED', 'Suspended')], max_length=16)),
                ('basis', models.CharField(choices=[('LEGACY_CONTINUITY', 'Legacy continuity'), ('CONTRACT', 'Approved contract'), ('TRIAL', 'Approved trial')], max_length=24)),
                ('effective_from', models.DateTimeField(default=django.utils.timezone.now)),
                ('effective_to', models.DateTimeField(blank=True, null=True)),
                ('reason', models.TextField()),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('creator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('organisation', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='trip.organisation')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('organisation', 'version'), name='unique_tenant_entitlement_version')],
            },
        ),
        migrations.CreateModel(
            name='TenantModuleSelection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.TextField()),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('version', models.PositiveIntegerField()),
                ('modules', models.JSONField()),
                ('creator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('organisation', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='trip.organisation')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('organisation', 'version'), name='unique_tenant_module_selection')],
            },
        ),
    ]
